### ISSUE TITLE
Handle local 503 error (curl exit code 0)

### ISSUE THREAD

**Issue by Napsty** [Napsty/check_es_system#20]
When the destination URL returns a 503 error, curl (might) exit with a status code 0:

```
++ curl -k -s --max-time 30 --basic -u user:secret http://localhost:9200/_cluster/stats
+ esstatus='<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>'
+ esstatusrc=0
```

Manual verification:

```
root@es:/# curl -s -o /dev/null -w "%{http_code}" -k -s --max-time 30 --basic -u user:secret http://localhost:9200/_cluster/stats
503root@es:/# echo $?
0
```

This situation will cause the plugin to fail with the following error:

```
root@es:/# /opt/check_es_system.sh -H localhost -P 9200 -t status -u user -p secret
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
json read error: line 1 column 1: '[' or '{' expected near '<'
```

**Comment by extrad** [comment]
I think there might be a regression with this fix. I'm constantly getting 503-errors and can't reproduce it with curl.
Example:
`(for loop  with the following parameters -  -S -H host -t status -u user -p password ):
ES SYSTEM OK - Elasticsearch Cluster is green (8 nodes, 4 data nodes, 924 shards, 27552428763 docs)|total_nodes=8;;;; data_nodes=4;;;; total_shards=924;;;; relocating_shards=0;;;; initializing_shards=0;;;; unassigned_shards=0;;;; docs=27552428763;;;;
ES SYSTEM CRITICAL - Elasticsearch not available: (host):9200 return error 503`

Meanwhile 
`curl -s -o /dev/null -w "%{http_code}" -k -s --max-time 30 --basic -u user:password https://host:9200/_cluster/stats`
always returns "200".

This doesn't occur on the previous "1.7" version.

**Comment by Napsty** [comment]
@extrad Interesting. Can you please create a new issue with your findings and also run `bash -xv ./check_es_system.sh ....` and attach the output into the new issue (obfuscate credentials).
