### ISSUE TITLE
readonly check does not work as expected

### ISSUE THREAD

**Issue by juanmancebo** [Napsty/check_es_system#26]
## Expected Behavior
The readonly check must produce ES SYSTEM CRITICAL output when an index have the setting index.blocks.read_only setted to true.

## Current Behavior
The readonly check produces ES SYSTEM OK output when an index have the setting index.blocks.read_only setted to true.

## Steps to Reproduce
1. ```curl -XPUT -k -u ${user}:${pass} ${proto}://${host}:${port}/${index}/_settings -H 'Content-Type: application/json' -d '{ "index": { "blocks.read_only": true } }'```
2. ```chmod +x check_es_system.sh```
3. ```./check_es_system.sh -H ${host} -P ${port} -S -u ${user} -p ${pass} -t readonly -i ${index}```

**Comment by Napsty** [comment]
Thanks for reporting the issue. I can confirm the bug and reproduce it:

```
root@elasticsearch:~# curl -u elastic:secret -XPUT 'localhost:9200/claudiotest' 
{"acknowledged":true,"shards_acknowledged":true,"index":"claudiotest"}

root@elasticsearch:~# curl -u elastic:secret -XPUT 'localhost:9200/claudiotest/_settings' -H 'Content-Type: application/json' -d '{ "index": { "blocks.read_only": true } }' 

root@elasticsearch:/usr/lib/nagios/plugins# curl -u elastic:secret 'localhost:9200/claudiotest/_settings'
{"claudiotest":{"settings":{"index":{"number_of_shards":"5","blocks":{"read_only":"true"},"provided_name":"claudiotest","creation_date":"1591628119713","number_of_replicas":"1","uuid":"5tQFbnlXTV2iy3u_WEDwYw","version":{"created":"6080699"}}}}}

root@elasticsearch:/usr/lib/nagios/plugins# ./check_es_system.sh -H localhost -u elastic -p secret -t readonly
ES SYSTEM OK - Elasticsearch Indexes (_all) are writeable
```

The same also happens when I run the plugin with your PR though. 

I'm currently checking why this happens.

**Comment by Napsty** [comment]
So the issue is that when running through `/_all` index settings, the json parsing runs into an error on the first index without a `read_only` or `read_only_allow_delete` key.  
With `jshon` I can solve this using the `-C` parameter. But I'm currently fighting with `jq` which I know much less. Once I figure this out, at least the fix will be fairly easy and both `read_only` or `read_only_allow_delete` can be combined in the original check.

**Comment by juanmancebo** [comment]
The PR works well with both parsers for monitor a specific index. The test you're doing with check_es_system.sh is not the same as the test you're doing with curl. With curl you're working with a specific index and with check_es_system.sh you're working with all indexes. Could you try specifying the index as a parameter?
By other hand, if you want to monitor all indexes, you can notice that the problem is with jshon; with jq it works well.

### Specific index monitoring
```
# curl -sXGET -k -u ${user}:${pass} ${proto}://${host}:${port}/${index}/_settings|jq
{
  "logstash-default-2020.05.06": {
    "settings": {
      "index": {
        "opendistro": {
          "index_state_management": {
            "policy_id": "delete_index_workflow"
          }
        },
        "refresh_interval": "5s",
        "number_of_shards": "1",
        "blocks": {
          "read_only": "true"
        },
        "provided_name": "logstash-default-2020.05.06",
        "creation_date": "1591356880389",
        "number_of_replicas": "1",
        "uuid": "gDLLoLWkTgSfR24bEupfkQ",
        "version": {
          "created": "7030299"
        }
      }
    }
  }
}
```
```
# ./check_es_system.sh -H ${host} -P ${port} -S -u ${user} -p ${pass} -t readonly -i ${index}
ES SYSTEM CRITICAL - Elasticsearch Index logstash-default-2020.05.06 is read_only (found 1 index(es) set to read_only)
```
```
# ./check_es_system.sh -H ${host} -P ${port} -S -u ${user} -p ${pass} -t readonly -i ${index} -X jq
ES SYSTEM CRITICAL - Elasticsearch Index logstash-default-2020.05.06 is read_only (found 1 index(es) set to read_only)
```
```
# md5sum check_es_system.sh 
2859ef41800f9c147ccb29cb91089d1b  check_es_system.sh
```
### All indexes
```
# ./check_es_system.sh -H ${host} -P ${port} -S -u ${user} -p ${pass} -t readonly  -X jq
ES SYSTEM CRITICAL - Elasticsearch Index _all is read_only (found 1 index(es) set to read_only)
```
```
# ./check_es_system.sh -H ${host} -P ${port} -S -u ${user} -p ${pass} -t readonly
ES SYSTEM OK - Elasticsearch Indexes (_all) are writeable
```

**Comment by Napsty** [comment]
I created the issue-26 branch an hour ago and this not only fixes the read only parsing with jshon, it also catches both read_only types (read_only and read_only_allow_delete). For me as an end user when I want to monitor for read only indexes, I want to catch both types in one check.
The output is slightly adjusted when all indexes are checked. Output of "Index _all is read_only" does not help much and could be confusing to the end user.

Tests:

```
$ ./check_es_system.sh -H localhost -u elastic -p k1b8n8 -t readonly
ES SYSTEM CRITICAL -  1 index(es) found read-only - 1 index(es) found read-only (allow delete) -
```

```
./check_es_system.sh -H localhost -u elastic -p k1b8n8 -t readonly -i claudiotest
ES SYSTEM CRITICAL -  claudiotest is read-only -
```

```
$ ./check_es_system.sh -H localhost -u elastic -p k1b8n8 -t readonly -i claudiotest2
ES SYSTEM CRITICAL -  claudiotest2 is read-only (allow delete) -
```

The output concatenation could look nicer but it allows to add multiple types of read_only indexes in the same output (see first test).

Could you please test https://raw.githubusercontent.com/Napsty/check_es_system/7327bc15059e618f297fca78c0ba22f816f69904/check_es_system.sh if it works correctly in your environment?
