### ISSUE TITLE
Output of tps too long

### ISSUE THREAD

**Issue by willemdh** [Napsty/check_es_system#28]
Hello,

Probably only in larger clusters, but when I run check_es_system.sh with tps type, I get a huge perfdata output. Not sure what would be a good workaround, maybe only return the sum of all queues? (with an option)

Grtz

Willem

**Comment by Napsty** [comment]
Yes, there can be many tps queues - the more cluster nodes, the more queues you get (for the whole cluster). 
We could add a parameter to limit the queues to certain? Like an "inclusive list"?

**Comment by Napsty** [comment]
Working on a PR now. Will re-use the already existing `-i` parameter.

**Comment by Napsty** [comment]
@willemdh  Please test with the PR #32 
Example:

```
$ ./check_es_system.sh -H myescluster -u user -p secret -t tps -i "watcher"
ES SYSTEM OK - Found 3 thread pools in cluster|tp_elastic02-p-watcher_active=0;;;; tp_elastic02-p-watcher_queue=0;;;; tp_elastic02-p-watcher_rejected=0;;;;  tp_elastic01-p-watcher_active=5;;;; tp_elastic01-p-watcher_queue=0;;;; tp_elastic01-p-watcher_rejected=0;;;;  tp_elastic03-p-watcher_active=0;;;; tp_elastic03-p-watcher_queue=0;;;; tp_elastic03-p-watcher_rejected=0;;;; 
```

**Comment by Napsty** [comment]
@willemdh Were you able to test the PR #32? Working on your environment?

**Comment by Napsty** [comment]
Assuming OK, could not find any issues on my own Elasticsearch instances. Going forward with PR.

**Comment by willemdh** [comment]
@Napsty Please give me a few weeks, very busy atm...

**Comment by Napsty** [comment]
@willemdh no problem - i already released it. :)
