### ISSUE TITLE
Minimal role to get the command working

### ISSUE THREAD

**Issue by nohaj** [Napsty/check_es_system#37]
Hello,

It's more a suggestion that an issue.

Maybe you could add to the documentation the permissions that the user need to to be able to use this script ?

Regards,

Johan

**Comment by Napsty** [comment]
Hi @nohaj , which permissions do you mean? The ones on Elasticsearch side? Or the plugin itself?

**Comment by nohaj** [comment]
The ones on Elasticsearch side =)

**Comment by silviuvulcan** [comment]
Silly question :) has this been documented ? What permissions should a user used by this plugin have?

**Comment by nohaj** [comment]
I ended up using the builtin role "monitor"

**Comment by Napsty** [comment]
Added to documentation: https://www.claudiokuenzler.com/monitoring-plugins/check_es_system.php#Privileges
